
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpetstore
    username: root
    password: ZpC498420459
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  servlet:
    context-path: /jpetstore
  port: 8888

logging:
  file:
    path: log

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com/example/jpetstore_manage/pojo/DataObject
  configuration:
    map-underscore-to-camel-case: true

#上传文件的相对位置
#(暂时无用)
image:
  uploadedImagePath: ./uploadedImage